name: Deploy to Pages

on:
  push:
    branches: [ "main" ] # Или ваша основная ветка

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v3
        with:
          lfs: true # ВОТ ЭТО КЛЮЧЕВОЙ МОМЕНТ - ВКЛЮЧАЕМ LFS

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # Укажите здесь нужную папку, например './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
